### ISSUE TITLE
Contribute to Emacs?

### ISSUE THREAD

**Issue by phil-s** [atomontage/xterm-color#10]
If this replaces and is better than ansi-color.el, would you contribute it to Emacs so that it can be used by default?

**Comment by atomontage** [comment]
At some point I will, but until then I'm looking to add more features such as support for
non color-related codes (move cursor to column/row, clear screen and so on) which are subsets
of full terminal emulation (that I may actually attempt too).

**Comment by phil-s** [comment]
Excellent. In the meantime please be cautious about accepting any pull requests from people who have not signed copyright assignment papers for Emacs -- doing so can make it hard to subsequently contribute code, as all contributors must assign copyright as well. Some well-meaning library authors have found it difficult or impractical to contribute their libraries later on, because they didn't have this in mind when accepting patches from others. Good luck with the new features and the terminal emulation!
