### ISSUE TITLE
add simple instructions to have it handle .txt files automatically

### ISSUE THREAD

**Issue by ginobean** [atomontage/xterm-color#14]
I installed 'xterm-color' using el-get and then tried to running M-x 'xterm-color-colorize-buffer' but emacs did not recognize that function. 

Can you write up simple instructions on how to set it up to enable xterm-color for *.txt files, as an example?

As a comparison, I followed a recipe for ansi-colors and am able to bring up *.txt files and have it automatically use ansi-colors. 

I was interested in using xterm-color for better performance, but seeing as I can't even get 'xterm-color-colorize-buffer' to work, I am unable to use xterm-color in even a basic fashion.

**Comment by atomontage** [comment]
M-x xterm-color-colorize-buffer works. Try without el-get.
