### ISSUE TITLE
Consider making xterm-color--256 "public"

### ISSUE THREAD

**Issue by dieggsy** [atomontage/xterm-color#15]
That is, rename it it `xterm-color-256`. I experimented with it to get 256 ansi-term color with a simple-ish hack (see edit 2 here: https://www.reddit.com/r/emacs/comments/6zngo4/ansiterm_256_color_hack/), so I'd say it's useful for more that just internal things.

**Comment by atomontage** [comment]
It's now exposed as xterm-color-256.

**Comment by dieggsy** [comment]
@atomontage for what it's worth, my "hack" is now a package: https://github.com/dieggsy/eterm-256color

**Comment by atomontage** [comment]
I still think term.el is garbage and not worth the trouble but hey, kudos :-)
IMO an approach similar to https://github.com/akermu/emacs-libvterm 
is the way to go in terms of having "good" terminal emulation inside Emacs.

**Comment by dieggsy** [comment]
@atomontage in general, I agree about it being garbage, but if i can make it a _bit_ more usable, why not heh.

And yeah I'd seen that earlier, would love to see it gain some more traction
