### ISSUE TITLE
Very first eshell prompt loses colors

### ISSUE THREAD

**Issue by dieggsy** [atomontage/xterm-color#16]
I have a customized eshell prompt with multiple colors - with xterm-color, the very first prompt loses all faces, but all subsequent prompts are fine. This is pretty minor, but do you know why this happens?

**Comment by dieggsy** [comment]
I found setting `xterm-color-preserve-properties` on `eshell-before-prompt-hook` (or defaulting it to `t`) does the right thing. Seems it needs to be set before the first prompt pops up, and setting it in `esehll-mode-hook` doesn't do this.

**Comment by atomontage** [comment]
Thanks, updated docs/comments in latest release.
