### ISSUE TITLE
Is it possible to make this work in M-x ansi-term?

### ISSUE THREAD

**Issue by peterhadlaw** [atomontage/xterm-color#2]
I have this working in shell but I really prefer using ansi-term. Is it possible to set this up in a way to also work there?

Thanks!

**Comment by atomontage** [comment]
Peter,

I started writing xterm-color as part of a bigger project
(a complete VT100 terminal emulator) that I didn't get to finish.
I then extracted the color handling and released xterm-color.el.

ansi-term (term.el really) does its own terminal emulation so
one would need to hook into its model of doing things in order
to add support for xterm 256 colors, so there's no straightforward
way that I see to get xterm-color.el working on top. You'd have
to add what's missing directly.

I would like to eventually finish my terminal emulator (which is
a lot faster than term.el) but then I look at the stack of
unfinished projects I have and confidence in me doing so evaporates :)

Chris

**Comment by peterhadlaw** [comment]
Chris,

Thanks for such a quick response. I definitely feel yah on that one. Thanks for contributing this to the community, I would help with things (even at least this) but I'm relatively new to emacsen land. Maybe in the future ;)

Have a good one!

**Comment by dieggsy** [comment]
@peterhadlaw  I sorta got 256 colors in ansi term with the help of a function from `xterm-color`. See post and edit #2 here: https://www.reddit.com/r/emacs/comments/6zngo4/ansiterm_256_color_hack/
