### ISSUE TITLE
Disable selected CSI codes in selected buffers

### ISSUE THREAD

**Issue by vapniks** [atomontage/xterm-color#20]
When I use `xterm-color-filter` in ipython comint buffers the prompts don't come out right because `xterm-color--dispatch-csi` handles "C" (forward cursor) but not "D" (backward cursor) which is perhaps unavoidable. I fixed the problem by redefining `xterm-color--dispatch-csi` in my startup file with  the code for handling "C" removed. However, this might actually be needed for other buffers.
It would be nice if there was a buffer local variable for disabling selected CSI codes (and maybe SGR codes?).

**Comment by atomontage** [comment]
I added xterm-color-ignore-movement (buffer-local, default: NIL) in latest release.

**Comment by vapniks** [comment]
Thanks!
