### ISSUE TITLE
Can't parse tput reset

### ISSUE THREAD

**Issue by azzamsa** [atomontage/xterm-color#24]
Hi

I just realize that the ugly trailing character in my emacs shell caused by `tput sgr0`. I use it to reset the colors in my urxvt which works fine. But in emacs shell it will look like this

``` bash
user at machine in /dir/foo
$ (B
```

After spending hours trying to figure it out. It was caused by `tput sgr0`. Changed it to `\e[0m` solved the problem.

Why xterm-color emacs can't parse `tput sgr0` ?

Thank you for xterm-color emacs.

**Comment by atomontage** [comment]
tput sgr0 output depends on your TERMINAL and its capabilities, not guaranteed to be \e[0m.
I am not emulating full xterm, just the color SGR attributes. So all of the xterm-specific sequences that are
not color-related will be skipped.  I may add more in the future.

```
❯❯ export TERM=xterm-256color
❯❯ tput sgr0 |hexdump -C
00000000  1b 28 42 1b 5b 6d                                 |.(B.[m|
❯❯ export TERM=ansi
❯❯ tput sgr0 |hexdump -C
00000000  1b 5b 30 3b 31 30 6d                              |.[0;10m|
```

**Comment by azzamsa** [comment]
>  So all of the xterm-specific sequences that are not color-related will be skipped. 

Ooh, okay.

> I may add more in the future.

Thank you for all hard work. thank you for xterm-color
