### ISSUE TITLE
Colorize "ls"

### ISSUE THREAD

**Issue by mrbig033** [atomontage/xterm-color#25]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-11-28
- Evil version 1.2.13
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- xterm-color-20180202.2318

#### Use-package

``` emacs-lisp
(use-package xterm-color
  :init
  (setq comint-output-filter-functions
	(remove 'ansi-color-process-output comint-output-filter-functions))
  (add-hook 'shell-mode-hook
	    (lambda () (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter nil t)))
  :ensure t)
```

#### Question

Is it possible to colorize the output of the command `ls`?

**Comment by atomontage** [comment]
Try:
```
ls --color=yes (on Linux)
ls -G (on macOS)
```
