### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Gooberpatrol66** [atomontage/xterm-color#26]
I don't understand the instructions. You provide an example configuration but you don't say what file to put it in.

**Comment by atomontage** [comment]
You place it in your personal init file: https://www.gnu.org/software/emacs/manual/html_node/eintr/Default-Configuration.html

**Comment by atomontage** [comment]
Here's a brief step-by-step:

+ Download xterm-color.el and copy it in a directory, example:
  "~/emacs/xterm-color.el"

+ In your .emacs, add:

  (add-to-list 'load-path "~/emacs/")
  (require 'xterm-color)

  ;; Add the rest of the customization that's described in
  ;; xterm-color.el documentation, depending on what you want
  ;; to customize.

+ Restart Emacs

+ Test that xterm-color.el is loaded and works:

  M-x xterm-color-test

**Comment by Gooberpatrol66** [comment]
xterm-color-test works now. M-x shell colors don't work though. Here's what I put in the init file:
```


nathan@gentoolaptop ~/.emacs.d $ cat init.el
(add-to-list 'load-path "~/.emacs.d/xterm-color/")
(require 'xterm-color)

(setq comint-output-filter-functions
      (remove 'ansi-color-process-output comint-output-filter-functions))

(add-hook 'shell-mode-hook
          (lambda () (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter nil t)))

;; Also set TERM accordingly (xterm-256color)

;; You can also use it with eshell (and thus get color output from system ls):

(require 'eshell)

(add-hook 'eshell-before-prompt-hook
          (lambda ()
            (setq xterm-color-preserve-properties t)))

(add-to-list 'eshell-preoutput-filter-functions 'xterm-color-filter)
(setq eshell-output-filter-functions (remove 'eshell-handle-ansi-color eshell-output-filter-functions))

;;  Don't forget to setenv TERM xterm-256color

(setq compilation-environment '("TERM=xterm-256color"))

(add-hook 'compilation-start-hook
          (lambda (proc)
            ;; We need to differentiate between compilation-mode buffers
            ;; and running as part of comint (which at this point we assume
            ;; has been configured separately for xterm-color)
            (when (eq (process-filter proc) 'compilation-filter)
              ;; This is a process associated with a compilation-mode buffer.
              ;; We may call `xterm-color-filter' before its own filter function.
              (set-process-filter
               proc
               (lambda (proc string)
                 (funcall 'compilation-filter proc
                          (xterm-color-filter string)))))))

```

**Comment by atomontage** [comment]
M-x shell

$ export TERM=xterm-256color

$ ls -la /dev/ --color=yes  (or if you're on macOS, ls -laG /dev/)
$ perl ~/.emacs.d/xterm-color/tests/xterm-colortest -w
$ perl ~/.emacs.d/xterm-color/tests/256colors2.pl

**Comment by Gooberpatrol66** [comment]
Ah, thanks. Is there a way to get PS1 colors to work?

**Comment by atomontage** [comment]
This is Emacs comint that highlights the prompt and overrides any existing face attributes.

You can do (set-face-attribute 'comint-highlight-prompt nil :inherit nil :foreground nil) but that will affect every comint-based buffer, where you may want to keep the Emacs prompt highlighting. I think the best way to do what you want, without modifying comint, is to change your shell prompt (PS1) to be multiline. Emacs will only highlight the last line, so you can put all your color in the first line.
