### ISSUE TITLE
Can't color specific text in shell (M-x shell)

### ISSUE THREAD

**Issue by lmdic** [atomontage/xterm-color#29]
Windows 10 (64 bit), Emacs 26.1

here my Emacs init.el

```
(require 'xterm-color)
(setq comint-output-filter-functions
      (remove 'ansi-color-process-output comint-output-filter-functions))

(add-hook 'shell-mode-hook
          (lambda () (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter nil t)))
```

Here Windows console. Result of build my project:

`gradlew assemble`
here result: 

![Q0oLu](https://user-images.githubusercontent.com/303539/57130271-9e080a00-6da1-11e9-8cbb-04f3e7ba4340.png)

Nice.
as you can see text **BUILD SUCCESSFUL** is on green color.

Nice.

Now same on Emacs's shell (`M-x shell`)
![zLYGi](https://user-images.githubusercontent.com/303539/57130362-ea534a00-6da1-11e9-8a0f-1911864c910f.png)

Is it possible also to green color text **BUILD SUCCESSFUL** in Emacs's shell forever?
Even after reset Emacs I want only text **BUILD SUCCESSFUL** in shell  to be green color.

Thanks

**Comment by atomontage** [comment]
Can you verify that "gradlew assemble" produces ANSI escapes when executed inside Emacs shell?
Something tells me that it doesn't (possibly by not detecting the Windows Console).

If the ANSI escapes are not there, xterm-color can not really render them as Emacs faces.

**Comment by lmdic** [comment]
> Can you verify that "gradlew assemble" produces ANSI escapes when executed inside Emacs shell?
> Something tells me that it doesn't (possibly by not detecting the Windows Console).
> 
> If the ANSI escapes are not there, xterm-color can not really render them as Emacs faces.

how I can check this?

**Comment by atomontage** [comment]
First, after running M-x shell try: export TERM=xterm-256color (in the shell)
and then run gradlew assemble again.

**Comment by lmdic** [comment]
> export TERM=xterm-256color

I get error:

```
export TERM=xterm-256color
'export' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by atomontage** [comment]
I forgot you were running cmd.exe on Windows. IIRC (but could be wrong since I don't use Windows) that the Windows Console does not support ANSI escapes, and programs use Windows-specific calls for color output. 

Maybe this helps: https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences

but I wouldn't expect gradlew to output ANSI on Windows.

I'm closing this for now. If you verify that ANSI escapes are indeed produced but not rendered, feel free to reopen.
