### ISSUE TITLE
support v2.wttr.in output

### ISSUE THREAD

**Issue by luogni** [atomontage/xterm-color#36]
Hi, I'm trying to use xterm-color to display http://v2.wttr.in/ but it doesn't seem to support all codes and the output is not perfect. 

I'm testing with:
```
(insert (xterm-color-filter (shell-command-to-string "curl -s v2.wttr.in/?0")))
```

**Comment by atomontage** [comment]
Try latest master, this is what it looks like here with PragmataPro:

![shot](https://user-images.githubusercontent.com/453886/80827750-3d78fc00-8bb2-11ea-8b88-9e5d9b1cbf6d.png)
