### ISSUE TITLE
How to correctly apply the filter to `make-process` buffer

### ISSUE THREAD

**Issue by ezchi** [atomontage/xterm-color#39]
Try to use filter on `make-process` as below:

    (let ((process-environment (add-to-list 'process-environment "TERM=xterm-256color")))
        (make-process :command (list "sh" "-c" "scons")
                                   :buffer "*foo*"
                                   :filter (lambda (_process string) (xterm-color-filter string))))

But I still not get color in the process buffer:

    ^[[90m# seed = random
    ^[[32m# Info ....

**Comment by atomontage** [comment]
The filter function needs to execute in the context of the given buffer (since it keeps buffer-local state). You can use something like:

```elisp
(with-current-buffer "*foo*" (insert (xterm-color-filter string)))
```
