### ISSUE TITLE
Symbol's function definition is void: first

### ISSUE THREAD

**Issue by talonchandler** [atomontage/xterm-color#9]
When I run ```xterm-color-test``` I receive the error:

```Symbol's function definition is void: first```

The offending code is in ```xterm-color.el``` line 257. 

I've installed xterm-color (and cl-lib) through the emacs package manager. I'm running GNU Emacs 25.0.95.1. 

Is there a hidden dependency, or am I doing something wrong?

Thanks!

**Comment by atomontage** [comment]
I've updated the code @ github to fix these issues
(that stem from cl.el -> cl-lib.el transition).

I'm not sure if the emacs package manager is tracking
my repo or if they cloned an earlier version and manually
syncing it. If the latter, you can either clone and use my github
repo directly or add (require 'cl) at the beginning of xterm-color.el
(not ideal but should fix your issues) that you got through
elpa/melpa etc

Chris

**Comment by talonchandler** [comment]
Fixed. Thank you so much!

FWIW melpa has an October 29 version, so it should update soon. 

Thanks for the great package.
